# Generated by Django 4.2.4 on 2023-09-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals', models.TextField()),
                ('caloric_intake', models.PositiveIntegerField()),
                ('nutrition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition_plans.nutritionplan')),
            ],
        ),
    ]
